import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    header: {
        paddingBottom: 20,
        paddingHorizontal: 24,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    greeting: {
        fontSize: 24,
        fontWeight: '600',
        color: '#ffffff',
    },
    subtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.9)',
        marginTop: 4,
    },
    settingsButton: {
        width: 40,
        height: 40,
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    statsContainer: {
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 16,
        backgroundColor: '#ffffff',
    },
    statCard: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 12,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    statIcon: {
        fontSize: 24,
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 11,
        color: '#6b7280',
        marginBottom: 4,
    },
    statValue: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
    },
    cardContainer: {
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 30,
        backgroundColor: '#ffffff',
    },
    profileCard: {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 6,
    },
    scrollContent: {
        flexGrow: 1,
        backgroundColor: '#ffffff',
    },
    imageContainer: {
        position: 'relative',
    },
    profileImage: {
        width: '100%',
        height: 400,
        backgroundColor: '#e5e7eb',
    },
    badgesContainer: {
        position: 'absolute',
        top: 16,
        left: 16,
        flexDirection: 'row',
        gap: 8,
    },
    verifiedBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#3b82f6',
        borderRadius: 16,
    },
    onlineBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#22c55e',
        borderRadius: 16,
    },
    badgeText: {
        color: '#ffffff',
        fontSize: 12,
        fontWeight: '600',
    },
    matchBadgeContainer: {
        position: 'absolute',
        top: 16,
        right: 16,
    },
    matchBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: 'rgba(255,255,255,0.95)',
        borderRadius: 16,
    },
    matchText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#f97316',
    },
    profileOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 24,
    },
    profileName: {
        fontSize: 24,
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: 4,
    },
    profileLocation: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.9)',
    },
    detailsContainer: {
        padding: 24,
    },
    detailsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 16,
    },
    detailBox: {
        width: '48%',
        backgroundColor: '#fef3f2',
        borderRadius: 12,
        padding: 14,
        borderWidth: 1,
        borderColor: '#fee2e2',
    },
    detailLabel: {
        fontSize: 12,
        color: '#f97316',
        marginBottom: 4,
    },
    detailValue: {
        fontSize: 14,
        fontWeight: '500',
        color: '#111827',
    },
    bio: {
        fontSize: 14,
        color: '#6b7280',
        lineHeight: 20,
        marginBottom: 16,
    },
    viewProfileButton: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#f97316',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    viewProfileText: {
        color: '#f97316',
        fontWeight: '500',
        fontSize: 15,
    },
    actionsContainer: {
        backgroundColor: '#ffffff',
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
        paddingHorizontal: 24,
        paddingTop: 20,
        paddingBottom: 20,
    },
    actionsRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 24,
        marginBottom: 8,
    },
    passButton: {
        width: 56,
        height: 56,
        backgroundColor: '#f3f4f6',
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    likeButton: {
        width: 80,
        height: 80,
        borderRadius: 40,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#f97316',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    profileButton: {
        width: 56,
        height: 56,
        backgroundColor: '#eff6ff',
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    actionsLabels: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 24,
    },
    actionLabel: {
        fontSize: 12,
        color: '#9ca3af',
        width: 56,
        textAlign: 'center',
    },
    actionLabelActive: {
        fontSize: 12,
        color: '#f97316',
        fontWeight: '600',
        width: 80,
        textAlign: 'center',
    },
});
