import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingBottom: 15,
    },
    backButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#ffffff',
        flex: 1,
        textAlign: 'center',
    },
    content: {
        flex: 1,
    },
    infoSection: {
        padding: 16,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    infoTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 8,
    },
    infoText: {
        fontSize: 14,
        color: '#6b7280',
    },
    photoGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding: 8,
    },
    photoCard: {
        width: '48%',
        aspectRatio: 0.75,
        margin: '1%',
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#ffffff',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    photoImage: {
        width: '100%',
        height: '100%',
    },
    profileBadge: {
        position: 'absolute',
        top: 8,
        left: 8,
        backgroundColor: '#f97316',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    profileBadgeText: {
        color: '#ffffff',
        fontSize: 10,
        fontWeight: '600',
    },
    deleteButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'rgba(239, 68, 68, 0.9)',
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addPhotoCard: {
        width: '48%',
        aspectRatio: 0.75,
        margin: '1%',
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        borderStyle: 'dashed',
        backgroundColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    addPhotoIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#fef3c7',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    addPhotoText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6b7280',
    },
    guidelinesSection: {
        margin: 16,
        padding: 16,
        backgroundColor: '#ffffff',
        borderRadius: 12,
    },
    guidelinesTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 12,
    },
    guidelineItem: {
        flexDirection: 'row',
        marginBottom: 8,
    },
    guidelineBullet: {
        fontSize: 14,
        color: '#f97316',
        marginRight: 8,
        fontWeight: 'bold',
    },
    guidelineText: {
        fontSize: 14,
        color: '#6b7280',
        flex: 1,
    },
});
