import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    header: {
        backgroundColor: '#ffffff',
        paddingBottom: 16,
        paddingHorizontal: 16,
    },
    title: {
        fontSize: 22,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 16,
    },
    searchRow: {
        flexDirection: 'row',
        gap: 12,
    },
    searchContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        paddingHorizontal: 12,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        height: 44,
        fontSize: 14,
        color: '#111827',
    },
    filterButton: {
        width: 44,
        height: 44,
        backgroundColor: '#f97316',
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        width: 20,
        height: 20,
        backgroundColor: '#1e3a8a',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterBadgeText: {
        color: '#ffffff',
        fontSize: 10,
        fontWeight: '600',
    },
    filterPanel: {
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    filterHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    filterTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    clearButton: {
        fontSize: 14,
        color: '#f97316',
        fontWeight: '500',
    },
    filterContent: {
        gap: 12,
    },
    filterLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
        marginBottom: 8,
    },
    filterRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 12,
    },
    filterInput: {
        flex: 1,
        height: 40,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        fontSize: 14,
        color: '#111827',
        backgroundColor: '#ffffff',
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        padding: 16,
        paddingBottom: 80,
        backgroundColor: '#f9fafb',
    },
    profileCard: {
        flexDirection: 'row',
        backgroundColor: '#ffffff',
        borderRadius: 16,
        marginBottom: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#f3f4f6',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    profileImage: {
        width: 90,
        height: 130,
        backgroundColor: '#e5e7eb',
        borderRadius: 12,
        margin: 8,
    },
    profileInfo: {
        flex: 1,
        padding: 12,
        paddingLeft: 4,
    },
    profileHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    profileNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    profileName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
    },
    verifiedBadge: {
        width: 20,
        height: 20,
        backgroundColor: '#3b82f6',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 4,
    },
    verifiedText: {
        color: '#ffffff',
        fontSize: 11,
        fontWeight: '600',
    },
    profileDetail: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginBottom: 4,
    },
    profileDetailText: {
        fontSize: 12,
        color: '#6b7280',
    },
    profileFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        gap: 8,
    },
    onlineDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#22c55e',
    },
    profileTags: {
        flexDirection: 'row',
        gap: 8,
        flex: 1,
    },
    heightTag: {
        fontSize: 11,
        color: '#f97316',
        fontWeight: '500',
    },
    dietTag: {
        fontSize: 11,
        color: '#22c55e',
        fontWeight: '500',
    },
    matchBadgeContainer: {
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    matchText: {
        fontSize: 11,
        color: '#3b82f6',
        fontWeight: '600',
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    emptyText: {
        fontSize: 16,
        color: '#9ca3af',
        textAlign: 'center',
    },
    resultsHeader: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#ffffff',
    },
    resultsText: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '500',
    },
});
