import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    scrollView: {
        flex: 1,
    },
    imageContainer: {
        position: 'relative',
    },
    profileImage: {
        width: '100%',
        height: 360,
        backgroundColor: '#e5e7eb',
    },
    backButton: {
        position: 'absolute',
        top: 15,
        left: 15,
        width: 40,
        height: 40,
        backgroundColor: 'rgba(255,255,255,0.9)',
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    matchBadge: {
        position: 'absolute',
        top: 15,
        right: 15,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#ffffff',
        borderRadius: 16,
    },
    matchText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#f97316',
    },
    verifiedTopBadge: {
        position: 'absolute',
        top: 15,
        right: 15,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#3b82f6',
        borderRadius: 16,
    },
    verifiedTopText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#ffffff',
    },
    contentContainer: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        marginTop: -24,
        position: 'relative',
    },
    content: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 24,
    },
    headerSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 28,
    },
    nameContainer: {
        flex: 1,
    },
    nameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    name: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginRight: 8,
    },
    verifiedBadge: {
        width: 18,
        height: 18,
        backgroundColor: '#3b82f6',
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    verifiedText: {
        color: '#ffffff',
        fontSize: 8,
        fontWeight: '600',
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 4,
    },
    infoText: {
        fontSize: 15,
        color: '#6b7280',
    },
    onlineBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#dcfce7',
        borderRadius: 12,
    },
    onlineText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#16a34a',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#dcfce7',
        borderRadius: 12,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#16a34a',
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#16a34a',
    },
    section: {
        marginBottom: 28,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionIcon: {
        fontSize: 22,
        marginRight: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 15,
        paddingBottom: 10,
    },
    bioText: {
        fontSize: 15,
        color: '#4b5563',
        lineHeight: 24,
        backgroundColor: '#fef3f2',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#fee2e2',
    },
    detailsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    detailItem: {
        width: '48%',
        backgroundColor: '#fef3f2',
        padding: 14,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#fee2e2',
    },
    detailLabel: {
        fontSize: 12,
        color: '#f97316',
        marginBottom: 6,
        fontWeight: '500',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    detailValue: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
        textTransform: 'capitalize',
    },
    familyDetails: {
        gap: 8,
    },
    familyText: {
        fontSize: 15,
        color: '#374151',
        lineHeight: 22,
    },
    actionButtons: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 24,
        paddingVertical: 16,
        backgroundColor: '#ffffff',
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 8,
        paddingBottom: 25,
    },
    interestButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#f97316',
        paddingVertical: 14,
        borderRadius: 12,
    },
    interestButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
    chatButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#3b82f6',
        paddingVertical: 14,
        borderRadius: 12,
    },
    chatButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
});
